- src/main/java/ca/team2706/frc/robot/config/Config.java
Static configuration is useful for creating constants that cannot be changed at runtime, but set based on the robot that the code is running on. The robot is identified by a file containing the index of the value to use.
> Add static configuration

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
- Added sensors that are on plyboy but not the real robot
- Only allocates when not already allocated
- Allocation table for easy modification of which sensors to allocate
- Tested multiple allocations
- Tested that `LiveWindow` entries are populated
**Environment**: Plyboy
> Plyboy test code on robot

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/config/FluidConstant.java
- Fixes #30.
- Fluid constants initialize on robot initialization.
- Fluid constants can be initialized later too.
Commented out all references to the config class and then initialized it in the teleop stage to see if it worked.
> Config manager/fluid initialize

- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
> Add merge light

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/commands/ArcadeDrive.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
- src/test/java/ca/team2706/frc/robot/subsystems/DriveBaseTest.java
Part of resolving #48.
- Fixes warning in analog selector
- Allows switching between drive modes
> Drivebase modes

- src/main/java/ca/team2706/frc/robot/sensors/AnalogSelector.java
- src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
- Remove extra sensors from sensor extras
- Remove analog input used in analog selector from live window
- Switch DIOs to DigitalInputs
Checked for warnings, ensure that the analog input isn't ungrouped, press button on plyboy to see that DIO is working
**Environment**: Plyboy
> Update sensors for plyboy, fix analog selector in live window

- build.gradle
- src/main/java/ca/team2706/frc/robot/fluidwrapper/FluidJoystickButton.java
- vendordeps/Phoenix.json
- Fixed format of build,gradle dependency
- Update to latest Phoenix library version
- Supports desktop deploy (`simulateJava` task)
- Allows for testing of Network Tables without robot
Program doesn't crash
**Environment**: Desktop Deploy
> Update Talons to latest version

- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/operatorfeedback/rumbler/RumblePattern.java
- src/main/java/ca/team2706/frc/robot/operatorfeedback/rumbler/Rumbler.java
- src/test/java/ca/team2706/frc/robot/operatorfeedback/rumbler/RumblerTest.java
- Add rumbler tests
- Fix up some of the rumbler class to make it more suitable for testing.
**Environment**: Automated tests
The changes made to the rumbler have been carefully reviewed and tested using the unit tests and shouldn't require an robot test.
> Rumbler tests

- src/main/java/ca/team2706/frc/robot/subsystems/Bling.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/main/resources/log4j2.xml
Changed info logs to debug logs
Says what each log is now
Logs to usb
Plyboy
> changed logs to debug, logs to usb now

- src/main/java/ca/team2706/frc/robot/commands/drivebase/DriveForwardWithTime.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/DriveForwardWithTimeTest.java
Created drive with time command
plyboy
> Drive forward with time command

- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/test/java/ca/team2706/frc/robot/RobotTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/ArcadeDriveTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/ArcadeDriveWithJoystickTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/DriveForwardWithTimeTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/StraightDriveTest.java
- src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
- src/test/java/ca/team2706/frc/robot/config/FluidConstantTest.java
- src/test/java/ca/team2706/frc/robot/input/EButtonTest.java
- src/test/java/ca/team2706/frc/robot/subsystems/DriveBaseTest.java
Does pretty much the same thing, and is provided by WPILib
**Environment**: Plyboy
> Use Notifier instead of Thread

- build.gradle
- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/commands/bling/BlingController.java
- src/main/java/ca/team2706/frc/robot/operatorfeedback/rumbler/Rumbler.java
- src/main/java/ca/team2706/frc/robot/subsystems/Bling.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/test/java/ca/team2706/frc/robot/subsystems/DriveBaseTest.java
Method to get absolute gyro heading
Closes #71 
> Add absolute gyro method

- src/main/java/ca/team2706/frc/robot/input/QuadrantButton.java
- src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
- src/test/java/ca/team2706/frc/robot/input/QuadrantButtonTest.java
Activates when the analog stick is in a triangle quadrant (up, down, right, left)
**Environment**:  Plyboy & CI
> Bring QuadrantButton over from 2018

- src/main/java/ca/team2706/frc/robot/Robot.java
Added functionality for two USB camera streams on the driver station 
**Environment**: 
Plyboy
> Added functionlity for two cameras

- src/main/java/ca/team2706/frc/robot/OI.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDrive.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystick.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystickTest.java
Implemented a tank drive mode for the robot
**Environment**: 
Plyboy
Azure Pipelines
> Added tank drive functionality

- build.gradle
- src/main/java/ca/team2706/frc/robot/config/Config.java
Update WPILib and switch gyro Talon ID
**Environment**:  Practice Bot
> Update WPILib and switch gyro Talon ID

- src/main/java/ca/team2706/frc/robot/OI.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDrive.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystick.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/config/XboxValue.java
- src/main/java/ca/team2706/frc/robot/input/FluidButton.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystickTest.java
- src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
- src/test/java/ca/team2706/frc/robot/config/FluidConstantTest.java
- src/test/java/ca/team2706/frc/robot/input/FluidButtonTest.java
- Moved the `XboxValue` enum to its own class.
- Added critical initialization for Config (bug fix)
- Added more tests to config to make sure certian things that should work work.
- Moved some utility methods from the `FluidButton` class to the `XboxValue` enum where they belonged.
- Added some utility methods to the `XboxValue` enum.
**Environment**: Plyboy and Practice bot
While working on intake mechanisms I made this change and the config stuff worked.
Deployed to practice bot and made sure constants table appeared and updated when it should.
> Config rework

- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystick.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystickTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
Fix motion magic control mode
Fix brake mode in curvature drive
> Fix motion magic control mode

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
Optionally disable the timer which prints a warning message.
**Environment**:  Simulation and practice bot
> Disable the loop overrun message

- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
Raised soft limit after hardware changes
Changed level 3 hatch setpoint
**Environment**: Practice Bot
> Lift setpoint changes

- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystickTest.java
Increase slowmode throttle and curve speed so that it can be used by the drivers
**Environment**:  Practice Bot
> Increase slowmode throttle

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/MotionMagic.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
Use separate PID parameters for motion magic
Use encoder distance for determining if finished
Can get to within about an inch tolerance
**Environment**: Practice Bot
> Tune motion magic parameters

- build.gradle
- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/logging/Log.java
- src/main/resources/log4j2.xml
Logs build info
Logs warning if changes since last commit to driver station
> Build info

- azure-pipelines.yml
- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/commands/bling/patterns/BlingPattern.java
- src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToPosition.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/input/FluidButton.java
- src/main/java/ca/team2706/frc/robot/logging/Log.java
- src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
- src/test/java/ca/team2706/frc/robot/RobotTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicVisionTest.java
- Swapped motor mappings
- Interrupt non default commands only in auto
- Extra logging
- Tuned lift height and made it robot-specific
**Environment**: Competition bot (except for minor post-comp fixes)
> Ryerson post comp

- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
Clear all trajectories from Talons before pushing new profile
> Fix motion profile not clearing

- src/main/java/ca/team2706/frc/robot/Robot.java
- src/main/java/ca/team2706/frc/robot/SubsystemStatus.java
- src/main/java/ca/team2706/frc/robot/subsystems/Bling.java
- src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
- src/main/java/ca/team2706/frc/robot/subsystems/Intake.java
- src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
- src/main/java/ca/team2706/frc/robot/subsystems/Pneumatics.java
- src/main/java/ca/team2706/frc/robot/subsystems/RingLight.java
- src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
- Log initialization results for all subsystems
- Check talons, encoders, gyro for drivebase
- Disable closed loop modes for drivebase if errors occur
- Check lift talon, encoder, and limit switch in initialization
- Disable closed loop motion for lift if errors occur
- Check intake Victor in initialization
**Environment**:  Practice bot
> Subsystem Initialization Checks

- azure-pipelines.yml
- Reenabled Linux build
**Environment**: CI
> Reenable linux build

- src/main/java/ca/team2706/frc/robot/OI.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystick.java
- src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftOnJoystick.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveTest.java
- src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystickTest.java
Allow for squaring of inputs
We found that we didn't want a deadzone on the forward value for now, although it might be necessary to explore at a later point so that the robot doesn't move forward if the analog stick on the controller is slightly offset.
Closes #132 and #134
> Square inputs

- src/main/java/ca/team2706/frc/robot/OI.java
- src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToSetpointOnPOV.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
- Fix last setpoint not resetting at the end of a command
- Disable vision bindings
- Tune lift and lift heights
**Environment**: Competition bot
> Changes from North Bay

- src/main/java/ca/team2706/frc/robot/config/Config.java
- Don't have two commands bound  to same button
- Closes #153 
**Environment**: None
> Rebind vision for cargo

- src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
- Puts the drivebase into brake mode when slow mode is active
- Closes #142 
> Drive with brake mode when slow mode is pressed

- src/main/java/ca/team2706/frc/robot/OI.java
- src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftOnJoystick.java
- src/main/java/ca/team2706/frc/robot/config/Config.java
- src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
- Lift PIDs tuned
- Closes #131.
- Add lift feed-forward.
- Add a specific config slot for motion magic vs hold lift position.
Tuned the PIDs and made sure the changes didn't break things.
> Tune lift pids
